### ISSUE TITLE
the "phase" metadata column must contain 0, 1, or 2, for all the CDS features

### ISSUE THREAD

**Issue by AlexWanghaoming** [Bioconductor/GenomicFeatures#7] opened 2018-06-24 04:12 UTC
When use makeTxdbFromGff(), I met this issue.But I check my gtf file,there is no problem with the 8th col. It contains only 0,1,2 for all CDS features.Could you please tell me what's the problem?
Regards，
Alex

**Comment by hpages** [comment] 2018-06-28 06:43
Is your file GTF or GFF3? Where is it coming from? How was it generated? Are you sure it is valid GTF or GFF3? Can you show some evidence that the phase column is correct?

Please show the exact code you used to read the file. We need to be able to run this code too so we need access to the file or to a subset of the file. Also please show the output of your `sessionInfo()`. We can't do much to help you if we can't reproduce the problem. Thanks!

**Comment by AlexWanghaoming** [comment] 2018-06-29 11:01
Thanks for your reply.
We make GTF file by ourself. Are the 8th column phase column，maybe I misunderstand the meaning of phase column though I have read your source code for GenomicFeatures. 
I read GTF file by : txdb <- makeTxDbFromGFF(file="/disk/wanghm/data/FG-ORF-hlq-flag-fix-nofusion5+PT.gtf",format=c("auto", "gff3", "gtf"),dataSource="gtf file for Fusarium_graminearum",organism="Fusarium Graminearum")

Some of my GTF file like this:
2       PacBio  transcript      2336332 2338948 .       +       .       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.7";
2       PacBio  exon    2336332 2336477 .       +       .       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.7";
2       PacBio  exon    2336527 2337417 .       +       .       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.7";
2       PacBio  exon    2337480 2337552 .       +       .       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.7";
2       PacBio  exon    2337605 2338340 .       +       .       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.7";
2       PacBio  exon    2338402 2338948 .       +       .       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.7";
2       FG      CDS     2335206 2336477 100     +       0       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.1";
2       FG      CDS     2336527 2337417 100     +       0       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.1";
2       FG      CDS     2337480 2337552 100     +       0       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.1";
2       FG      CDS     2337605 2338340 100     +       1       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.1";
2       FG      CDS     2338402 2338774 100     +       2       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.1";
2       FG      CDS     2335206 2336477 100     +       0       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.5";
2       FG      CDS     2336527 2337417 100     +       0       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.5";
2       FG      CDS     2337480 2337593 100     +       0       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.5";
2       FG      CDS     2336334 2336477 100     +       0       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.7";
2       FG      CDS     2336527 2337417 100     +       0       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.7";
2       FG      CDS     2337480 2337552 100     +       0       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.7";
2       FG      CDS     2337605 2338340 100     +       1       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.7";
2       FG      CDS     2338402 2338774 100     +       2       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.7";
2       FG      CDS     2335206 2336477 100     +       0       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.2";
2       FG      CDS     2336527 2337417 100     +       0       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.2";
2       FG      CDS     2337480 2337552 100     +       0       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.2";
2       FG      CDS     2337605 2338340 100     +       1       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.2";
2       FG      CDS     2338402 2338774 100     +       2       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.2";
2       FG      CDS     2335206 2336477 100     +       0       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.6";
2       FG      CDS     2336527 2337417 100     +       0       gene_id "FGRRES_08702"; transcript_id "FGRRES_08702.6";
And my session.info() is 👍 
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.9 (Final)

Matrix products: default
BLAS: /opt/R-3.5.0/lib64/R/lib/libRblas.so
LAPACK: /opt/R-3.5.0/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
  [1] bitops_1.0-6                           
  [2] matrixStats_0.53.1                     
  [3] enrichplot_1.0.2                       
  [4] bit64_0.9-7                            
  [5] RColorBrewer_1.1-2                     
  [6] progress_1.2.0                         
  [7] httr_1.3.1                             
  [8] GenomeInfoDb_1.16.0                    
  [9] UpSetR_1.3.3                           
 [10] tools_3.5.0                            
 [11] R6_2.2.2                               
 [12] KernSmooth_2.23-15                     
 [13] DBI_1.0.0                              
 [14] lazyeval_0.2.1                         
 [15] BiocGenerics_0.26.0                    
 [16] colorspace_1.3-2                       
 [17] tidyselect_0.2.4                       
 [18] gridExtra_2.3                          
 [19] prettyunits_1.0.2                      
 [20] compiler_3.5.0                         
 [21] bit_1.1-14                             
 [22] Biobase_2.40.0                         
 [23] DelayedArray_0.6.1                     
 [24] rtracklayer_1.40.3                     
 [25] caTools_1.17.1                         
 [26] scales_0.5.0                           
 [27] ChIPseeker_1.16.0                      
 [28] ggridges_0.5.0                         
 [29] stringr_1.3.1                          
 [30] digest_0.6.15                          
 [31] Rsamtools_1.32.0                       
 [32] DOSE_3.6.0                             
 [33] XVector_0.20.0                         
 [34] pkgconfig_2.0.1                        
 [35] plotrix_3.7-2                          
 [36] rlang_0.2.1                            
 [37] RSQLite_2.1.1                          
 [38] TxDb.Hsapiens.UCSC.hg19.knownGene_3.2.2
 [39] bindr_0.1.1                            
 [40] gtools_3.5.0                           
 [41] BiocParallel_1.14.1                    
 [42] GOSemSim_2.6.0                         
 [43] dplyr_0.7.5                            
 [44] RCurl_1.95-4.10                        
 [45] magrittr_1.5                           
 [46] GO.db_3.6.0                            
 [47] GenomeInfoDbData_1.1.0                 
 [48] Matrix_1.2-14                          
 [49] Rcpp_0.12.17                           
 [50] munsell_0.5.0                          
 [51] S4Vectors_0.18.3                       
 [52] viridis_0.5.1                          
 [53] stringi_1.2.3                          
 [54] ggraph_1.0.1                           
 [55] MASS_7.3-49                            
 [56] SummarizedExperiment_1.10.1            
 [57] zlibbioc_1.26.0                        
 [58] gplots_3.0.1                           
 [59] plyr_1.8.4                             
 [60] qvalue_2.12.0                          
 [61] grid_3.5.0                             
 [62] blob_1.1.1                             
 [63] gdata_2.18.0                           
 [64] parallel_3.5.0                         
 [65] ggrepel_0.8.0                          
 [66] DO.db_2.9                              
 [67] crayon_1.3.4                           
 [68] lattice_0.20-35                        
 [69] Biostrings_2.48.0                      
 [70] cowplot_0.9.2                          
 [71] splines_3.5.0                          
 [72] GenomicFeatures_1.32.0                 
 [73] hms_0.4.2                              
 [74] pillar_1.2.3                           
 [75] fgsea_1.6.0                            
 [76] igraph_1.2.1                           
 [77] GenomicRanges_1.32.3                   
 [78] boot_1.3-20                            
 [79] reshape2_1.4.3                         
 [80] biomaRt_2.36.1                         
 [81] stats4_3.5.0                           
 [82] fastmatch_1.1-0                        
 [83] XML_3.98-1.11                          
 [84] glue_1.2.0                             
 [85] data.table_1.11.4                      
 [86] tweenr_0.1.5                           
 [87] gtable_0.2.0                           
 [88] purrr_0.2.5                            
 [89] assertthat_0.2.0                       
 [90] ggplot2_2.2.1                          
 [91] gridBase_0.4-7                         
 [92] ggforce_0.1.2                          
 [93] viridisLite_0.3.0                      
 [94] tibble_1.4.2                           
 [95] GenomicAlignments_1.16.0               
 [96] AnnotationDbi_1.42.1                   
 [97] memoise_1.1.0                          
 [98] IRanges_2.14.10                        
 [99] units_0.6-0                            
[100] bindrcpp_0.2.2   
Thanks for your attention!
Regards，
Alex

**Comment by hpages** [comment] 2018-07-03 09:38
I don't see any problem with the file sample you're showing. All the CDS lines have a phase that is set to 0, 1, or 2, which is as expected.

In order for us to help, we need to be able to reproduce the problem. So please provide a reproducible example, that is, code that we can run. We can't run the code you provide above because we don't have access to `/disk/wanghm/data/FG-ORF-hlq-flag-fix-nofusion5+PT.gtf`

Also please try to make the code of your reproducible example as minimalist as possible and make sure that you can run it in a fresh R session. Good practice is to run `sessionInfo()` right after you run your own minimalist code in a fresh R session. This will also keep the output of `sessioninfo()` minimalist. Showing us an output polluted with more than 50 packages that have no relation with the issue being discussed doesn't help and is distracting.

Thanks!

**Comment by hpages** [comment] 2018-08-07 17:46
Hi @AlexWanghaoming ,

Are you planning to follow up on this issue? If not we will close it in a few days. Thanks!

H.

**Comment by Roleren** [comment] 2018-08-09 13:01
Here is a small example that I think it should be able to handle:

library(GenomicFeatures)
txdbFile <- system.file("extdata", "hg19_knownGene_sample.sqlite",  package = "GenomicFeatures")
txdb <- loadDb(txdbFile)
rtracklayer::export(txdb, "../ranges.gtf", "gtf") # set path to something else if you want
a <- makeTxDbFromGFF("../ranges.gtf")

Error in .get_cds_IDX(type, phase) : 
  the "phase" metadata column must contain 0, 1, or 2, for all the CDS features

sessionInfo()
R version 3.5.0 alpha (2018-04-03 r74516)
Platform: i686-pc-linux-gnu (32-bit)
Running under: Ubuntu 16.04.5 LTS

Matrix products: default
BLAS: /home/roler/R/i686-pc-linux-gnu-library/R-alpha/lib/libRblas.so
LAPACK: /home/roler/R/i686-pc-linux-gnu-library/R-alpha/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=nb_NO.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=nb_NO.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=nb_NO.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=nb_NO.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] BSgenome.Hsapiens.UCSC.hg19_1.4.0 BSgenome_1.49.3                   rtracklayer_1.41.3               
 [4] Biostrings_2.49.0                 XVector_0.21.3                    GenomicFeatures_1.33.0           
 [7] AnnotationDbi_1.43.1              Biobase_2.41.2                    GenomicRanges_1.33.11            
[10] GenomeInfoDb_1.17.1               IRanges_2.15.16                   S4Vectors_0.19.19                
[13] BiocGenerics_0.27.1              

loaded via a namespace (and not attached):
 [1] DBI_1.0.0                   Rsamtools_1.33.3            zlibbioc_1.27.0             bitops_1.0-6               
 [5] SummarizedExperiment_1.11.6 bit_1.1-14                  lattice_0.20-35             RSQLite_2.1.1              
 [9] pkgconfig_2.0.1             DelayedArray_0.7.22         blob_1.1.1                  compiler_3.5.0             
[13] stringr_1.3.1               GenomicAlignments_1.17.3    prettyunits_1.0.2           biomaRt_2.37.3             
[17] Rcpp_0.12.18                GenomeInfoDbData_1.1.0      httr_1.3.1                  progress_1.2.0             
[21] tools_3.5.0                 RCurl_1.95-4.11             BiocParallel_1.15.8         memoise_1.1.0              
[25] R6_2.2.2                    assertthat_0.2.0            digest_0.6.15               Matrix_1.2-14              
[29] stringi_1.2.4               rstudioapi_0.7              hms_0.4.2                   bit64_0.9-7                
[33] XML_3.98-1.13               grid_3.5.0                  rlang_0.2.1                 magrittr_1.5               
[37] yaml_2.2.0                  crayon_1.3.4                matrixStats_0.54.0

**Comment by hpages** [comment] 2018-08-13 18:56
Thanks @Roleren for the reproducible example.

Note that your example illustrates a problem that is slightly different from what @AlexWanghaoming  originally described. In your case the input file does NOT contain phase information (this is easy to check) and the error you get is accurately reporting that. Whereas @AlexWanghaoming was getting the same error but with a file where (according to his claim) the 8th column was containing "only 0,1,2 for all CDS features", that is, where the phase information was supposedly present and correct. So in your case the error message is a true positive but in @AlexWanghaoming's case it sounded like a false positive. Without access to @AlexWanghaoming's file, I'm still not in a position to confirm and troubleshoot the false positive issue.

As for your example, I agree that `makeTxDbFromGFF()` should be able to read GFF or GTF files created with `rtracklayer::export()`. Since TxDb objects generally don't contain the phase information (except in some situations), exporting them with `rtracklayer::export()` creates GFF files where the CDS phase is missing. This is unfortunately a violation of the GFF specs. I've modified `rtracklayer::export()` to issue a warning when this happens. I also replaced the error with a warning in `makeTxDbFromGFF()` when CDS phases are missing or not between 0 and 2.

With these changes:
```
library(GenomicFeatures)
txdbFile <- system.file("extdata", "hg19_knownGene_sample.sqlite", package = "GenomicFeatures")
txdb <- loadDb(txdbFile)
rtracklayer::export.gff3(txdb, "test.gff")
# Warning message:
# In .local(object, con, format, ...) :
#   The phase information is missing. The written file will contain CDS
#   with no phase information.
txdb2 <- makeTxDbFromGFF("test.gff")
# Import genomic features from the file as a GRanges object ... OK
# Prepare the 'metadata' data frame ... OK
# Make the TxDb object ... OK
# Warning message:
# In .get_cds_IDX(type, phase) :
#   some CDS phases are missing or not between 0 and 2
```
These changes are in rtracklayer 1.40.4 / 1.41.4, and in GenomicFeatures 1.32.2 / 1.33.2.

H.

**Comment by Roleren** [comment] 2018-08-14 08:58
I guess the issue can be closed then ? By the way, does there exist functions to fill in these columns that are missing ? CDS phase could easily be calculated by some wrapper function right ?

**Comment by hpages** [comment] 2018-08-14 14:53
Only if the gene model is _complete_ i.e. if all the CDS are known. There was an extensive discussion on our support site about this:a few months ago: https://support.bioconductor.org/p/101245/
See in particular the `addCdsPhase()` helper for inferring the CDS phase. I got distracted and didn't integrate `addCdsPhase()` to `cdsBy(txdb, by="tx")` yet, sorry. I'll open another issue here to remind me about this.

**Closed by hpages** 2018-08-14 14:53 UTC
