### ISSUE TITLE
makeTxDbFromUCSC fails to connect to UCSC server

### ISSUE THREAD

**Issue by ameliaregina** [Bioconductor/GenomicFeatures#50] opened 2022-06-06 05:06 UTC
Hi, I have been getting this error and am unsure how to resolve it as I don't seem to see anyone else encountering this issue.
```
> hg38.refseq.db <- makeTxDbFromUCSC(genome="hg38", table="refGene")
Download the refGene table ... Error: Failed to connect: Can't connect to server on 'genome-mysql.soe.ucsc.edu' (10061)
OK
```

Apologies if it is a trivial issue but I have tried updating everything and restarting my sessions yet nothing seems to be working. I don't think it is a wifi issue since I am able to run `browseUCSCtrack("hg38", "refGene")` fine, though I'm not sure how else to check it. I am currently using GenomicFeatures version 1.48.3 on R version 4.2.0 if it is relevant.

**Comment by hpages** [comment] 2022-06-08 04:57
Hi,

`makeTxDbFromUCSC()` uses **RMariaDB** behind the scene to query the MySQL server running at `genome-mysql.soe.ucsc.edu`. Does the following work for you?

    library(RMariaDB)
    dbconn <- dbConnect(RMariaDB::MariaDB(), dbname="hg38", username="genome", host="genome-mysql.soe.ucsc.edu", port=3306)
    dbconn
    # <MariaDBConnection>
    #   Host:    genome-mysql.soe.ucsc.edu
    #   Server:  
    #   Client:  
    dbDisconnect(dbconn)

Works for me.

H.

**sessionInfo():**
```
R version 4.2.0 (2022-04-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04 LTS

Matrix products: default
BLAS:   /home/hpages/R/R-4.2.0/lib/libRblas.so
LAPACK: /home/hpages/R/R-4.2.0/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB              LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RMariaDB_1.2.1

loaded via a namespace (and not attached):
 [1] bit_4.0.4       compiler_4.2.0  ellipsis_0.3.2  generics_0.1.2 
 [5] cli_3.3.0       hms_1.1.1       DBI_1.1.2       Rcpp_1.0.8.3   
 [9] bit64_4.0.5     lubridate_1.8.0 vctrs_0.4.1     lifecycle_1.0.1
[13] pkgconfig_2.0.3 rlang_1.0.2    
```

**Comment by ameliaregina** [comment] 2022-06-08 06:12
Thanks for your reply! That does not work for me either and similarly gives the error message: `Error: Failed to connect: Can't connect to server on 'genome-mysql.soe.ucsc.edu' (10061)`. I have tried this on my local computer, my colleague's computer, as well as a remote server and they all give the same error when doing dbConnect and consequently MakeTxDbFromUCSC. 

Here are the traceback() and sessionInfo() if relevant:
```
5: stop(structure(list(message = "Failed to connect: Can't connect to server on 'genome-mysql.soe.ucsc.edu' (10061)", 
       call = NULL, cppstack = NULL), class = c("Rcpp::exception", 
   "C++Error", "error", "condition")))
4: connection_create(host, username, password, dbname, as.integer(port), 
       unix.socket, as.integer(client.flag), groups, default.file, 
       ssl.key, ssl.cert, ssl.ca, ssl.capath, ssl.cipher, timeout)
3: .local(drv, ...)
2: dbConnect(RMariaDB::MariaDB(), dbname = "hg38", username = "genome", 
       host = "genome-mysql.soe.ucsc.edu", port = 3306)
1: dbConnect(RMariaDB::MariaDB(), dbname = "hg38", username = "genome", 
       host = "genome-mysql.soe.ucsc.edu", port = 3306)
```
```
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_Singapore.utf8  LC_CTYPE=English_Singapore.utf8   
[3] LC_MONETARY=English_Singapore.utf8 LC_NUMERIC=C                      
[5] LC_TIME=English_Singapore.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RMariaDB_1.2.1 biomaRt_2.52.0

loaded via a namespace (and not attached):
 [1] KEGGREST_1.36.0        progress_1.2.2         tidyselect_1.1.2      
 [4] purrr_0.3.4            vctrs_0.4.1            generics_0.1.2        
 [7] stats4_4.2.0           BiocFileCache_2.4.0    utf8_1.2.2            
[10] blob_1.2.3             XML_3.99-0.9           rlang_1.0.2           
[13] pillar_1.7.0           glue_1.6.2             DBI_1.1.2             
[16] rappdirs_0.3.3         BiocGenerics_0.42.0    bit64_4.0.5           
[19] dbplyr_2.2.0           GenomeInfoDbData_1.2.8 lifecycle_1.0.1       
[22] stringr_1.4.0          zlibbioc_1.42.0        Biostrings_2.64.0     
[25] memoise_2.0.1          Biobase_2.56.0         IRanges_2.30.0        
[28] fastmap_1.1.0          GenomeInfoDb_1.32.2    curl_4.3.2            
[31] AnnotationDbi_1.58.0   fansi_1.0.3            Rcpp_1.0.8.3          
[34] filelock_1.0.2         cachem_1.0.6           S4Vectors_0.34.0      
[37] XVector_0.36.0         bit_4.0.4              hms_1.1.1             
[40] png_0.1-7              digest_0.6.29          stringi_1.7.6         
[43] dplyr_1.0.9            cli_3.3.0              tools_4.2.0           
[46] bitops_1.0-7           magrittr_2.0.3         RCurl_1.98-1.6        
[49] RSQLite_2.2.14         tibble_3.1.7           crayon_1.5.1          
[52] pkgconfig_2.0.3        ellipsis_0.3.2         xml2_1.3.3            
[55] prettyunits_1.1.1      assertthat_0.2.1       httr_1.4.3            
[58] R6_2.5.1               compiler_4.2.0        
```

**Comment by hpages** [comment] 2022-06-08 16:36
It sometimes fails for me too but trying again eventually works:
```
library(RMariaDB)

dbconn <- dbConnect(RMariaDB::MariaDB(), dbname="hg38", username="genome", host="genome-mysql.soe.ucsc.edu", port=3306)
# Error: Failed to connect: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110

dbconn <- dbConnect(RMariaDB::MariaDB(), dbname="hg38", username="genome", host="genome-mysql.soe.ucsc.edu", port=3306)
dbconn
# <MariaDBConnection>
#   Host:    genome-mysql.soe.ucsc.edu
#   Server:  
#   Client:  
```
Hard to know why this happens. Could be a problem on UCSC's side with their MySQL server, or a flaky internet connection (I'm at home and my internet connection is definitely not the best), or a firewall policy at your institution that is blocking those requests, or a problem in **RMariaDB** itself.

To further narrow this down, try to use the `mysql` client at the command line (i.e. in a terminal). If you are on an Ubuntu system, you'll need to install `mysql-client-core-8.0` or `mariadb-client-core-10.6` to get the `mysql` client if you don't have it yet. On my machine:
```
hpages@spectre:~$ mysql -A --host=genome-mysql.soe.ucsc.edu --user=genome hg38
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 6827914
Server version: 10.3.28-MariaDB MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [hg38]> select name,chrom,strand,txStart,txEnd from refGene limit 5;
+-----------+-------+--------+---------+-------+
| name      | chrom | strand | txStart | txEnd |
+-----------+-------+--------+---------+-------+
| NR_024540 | chr1  | -      |   14361 | 29370 |
| NR_106918 | chr1  | -      |   17368 | 17436 |
| NR_107062 | chr1  | -      |   17368 | 17436 |
| NR_107063 | chr1  | -      |   17368 | 17436 |
| NR_128720 | chr1  | -      |   17368 | 17436 |
+-----------+-------+--------+---------+-------+
5 rows in set (0.060 sec)

MariaDB [hg38]> 
```
Does this work for you? If it does, then the problem is likely to be with **RMariaDB** itself and you should report it [here](https://github.com/r-dbi/RMariaDB/issues). If it doesn't, then the problem is likely to be with the firewall policy at your institution or with your internet connection.

Oh but I see that you are on Windows. Are your colleagues also on Windows and the remote server that you used to do the testing also a Windows machine?

H.

**Comment by hpages** [comment] 2022-06-10 19:23
@ameliaregina Have you been able to make progress on this? This isn't really a **GenomicFeatures** problem but more of a **RMariaDB** problem or a problem with your internet connection/setup. If we don't hear back from you in the next few days we'll close the issue.

H.

**Comment by ameliaregina** [comment] 2022-06-11 16:35
Apologies for the delayed response. I've tried to connect to MariaDB using ubuntu as you've demonstrated but it doesn't seem to work either so yes it is an issue with the firewall instead of GenomicFeatures. I still have yet to find out a fix but thank you for your help and feel free to close the issue.

**Comment by hpages** [comment] 2022-06-30 23:23
ok, good luck!

**Closed by hpages** 2022-06-30 23:23 UTC
