### ISSUE TITLE
GenomicFeatures fails to install on CentOS 7.4 w MariaDB

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/GenomicFeatures#4] opened 2017-12-19 23:48 UTC
See [this issue][1], originally opened on VariantAnnotation.

[1]: https://github.com/Bioconductor/VariantAnnotation/issues/1

**Comment by hpages** [comment] 2017-12-20 01:50
This is an RMySQL issue and it looks like it was fixed: https://github.com/r-dbi/RMySQL/issues/214

@datakid can you please confirm that you can now install GenomicFeatures on CentOS 7.4 w MariaDB? Thanks!

It's on our TODO list to migrate GenomicFeatures to use RMariaDB instead of RMySQL. Will happen in BioC devel at some point but BioC 3.6 is the current stable release and won't be touched.

**Comment by datakid** [comment] 2017-12-20 02:00
I can confirm that it installed - but I will again note that I had to use the fork, since the mainline package hasn't merged the pull request yet.

>    devtools::install_github("alecuba16/RMySQL")

**Comment by hpages** [comment] 2017-12-20 02:02
Thanks @datakid . From a GenomicFeatures point of view, the issue can be considered closed.

**Closed by hpages** 2017-12-20 02:02 UTC
