### ISSUE TITLE
`makeTxDbFromBiomart()` on the Ensembl archive version failed 

### ISSUE THREAD

**Issue by timedreamer** [Bioconductor/GenomicFeatures#57] opened 2023-05-05 16:42 UTC
Hi there,
I'm having trouble with `makeTxDbFromBiomart()` on the archive version of the Ensembl Plant.

I hope to use a older version of maize genome at *https://nov2020-plants.ensembl.org*. Below is my function call:

```r
zmv4_txdb <- makeTxDbFromBiomart(dataset="zmays_eg_gene", 
                             biomart="plants_mart",
                             host="https://nov2020-plants.ensembl.org")
zmv4_txdb
```

Although it says **Ensembl Plants Genes 49** which uses **RefGen_v4**, the content is actually the newest version from **Zm-B73-REFERENCE-NAM-5.0** (as you can see below). I wonder how to let `makeTxDbFromBiomart()` work on the older version of Ensembl Plant if possible?

```
TxDb object:
# Db type: TxDb
# Supporting package: GenomicFeatures
# Data source: BioMart
# Organism: Zea mays
# Taxonomy ID: 4577
# Resource URL: plants.ensembl.org:443
# BioMart database: plants_mart
# BioMart database version: Ensembl Plants Genes 49
# BioMart dataset: zmays_eg_gene
# BioMart dataset description: Zea mays genes (Zm-B73-REFERENCE-NAM-5.0)
# BioMart dataset version: Zm-B73-REFERENCE-NAM-5.0
# Full dataset: yes
# miRBase build ID: NA
# Nb of transcripts: 77341
# Db created by: GenomicFeatures package from Bioconductor
# Creation time: 2023-05-05 12:37:16 -0400 (Fri, 05 May 2023)
# GenomicFeatures version at creation time: 1.50.4
# RSQLite version at creation time: 2.2.18
# DBSCHEMAVERSION: 1.2
```

The search call returned the correct version.

```r
listMarts(host="https://nov2020-plants.ensembl.org")
datasets <- listDatasets(useMart(biomart="plants_mart",
                                 host="https://nov2020-plants.ensembl.org"))
subset(datasets, grepl("mays", dataset, ignore.case=TRUE))

#         dataset                    description       version
# 96 zmays_eg_gene Zea mays genes (B73 RefGen_v4) B73 RefGen_v4
```
Thanks!
Ji

**Comment by lshep** [comment] 2023-05-17 16:42
Can you include your `sessionInfo()`  and what version of R/Bioc you are using?

**Comment by timedreamer** [comment] 2023-05-17 17:02
Hi!

Here is my `sessionInfo()`. The R version is `4.2.2` and Bioc version is `3.16`.
BTW, I ended up using `makeTxDbFromGFF()` which is fine.
Thanks!
Ji

```
> sessionInfo()
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    
system code page: 65001

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets 
[7] methods   base     

other attached packages:
[1] GenomicFeatures_1.50.4 AnnotationDbi_1.60.0  
[3] Biobase_2.58.0         GenomicRanges_1.50.1  
[5] GenomeInfoDb_1.34.7    IRanges_2.32.0        
[7] S4Vectors_0.36.0       BiocGenerics_0.44.0   

loaded via a namespace (and not attached):
 [1] matrixStats_0.62.0          bitops_1.0-7               
 [3] lubridate_1.9.0             bit64_4.0.5                
 [5] filelock_1.0.2              progress_1.2.2             
 [7] httr_1.4.4                  tools_4.2.2                
 [9] backports_1.4.1             utf8_1.2.2                 
[11] R6_2.5.1                    DBI_1.1.3                  
[13] colorspace_2.0-3            withr_2.5.0                
[15] tidyselect_1.2.0            prettyunits_1.1.1          
[17] bit_4.0.4                   curl_4.3.3                 
[19] compiler_4.2.2              cli_3.4.1                  
[21] formatR_1.12                xml2_1.3.3                 
[23] DelayedArray_0.24.0         rtracklayer_1.58.0         
[25] scales_1.2.1                readr_2.1.3                
[27] rappdirs_0.3.3              Rsamtools_2.14.0           
[29] stringr_1.4.1               digest_0.6.30              
[31] rmarkdown_2.18              XVector_0.38.0             
[33] pkgconfig_2.0.3             htmltools_0.5.3            
[35] MatrixGenerics_1.10.0       dbplyr_2.3.0               
[37] fastmap_1.1.0               rlang_1.0.6                
[39] readxl_1.4.1                rstudioapi_0.14            
[41] RSQLite_2.2.18              BiocIO_1.8.0               
[43] generics_0.1.3              BiocParallel_1.32.1        
[45] dplyr_1.0.10                RCurl_1.98-1.9             
[47] magrittr_2.0.3              GenomeInfoDbData_1.2.9     
[49] Matrix_1.5-1                futile.logger_1.4.3        
[51] Rcpp_1.0.9                  munsell_0.5.0              
[53] fansi_1.0.3                 lifecycle_1.0.3            
[55] stringi_1.7.8               yaml_2.3.6                 
[57] snakecase_0.11.0            SummarizedExperiment_1.28.0
[59] zlibbioc_1.44.0             BiocFileCache_2.6.0        
[61] grid_4.2.2                  blob_1.2.3                 
[63] parallel_4.2.2              crayon_1.5.2               
[65] lattice_0.20-45             Biostrings_2.66.0          
[67] cowplot_1.1.1               hms_1.1.2                  
[69] KEGGREST_1.38.0             knitr_1.41                 
[71] pillar_1.8.1                rjson_0.2.21               
[73] codetools_0.2-18            biomaRt_2.54.0             
[75] futile.options_1.0.1        XML_3.99-0.12              
[77] glue_1.6.2                  evaluate_0.18              
[79] lambda.r_1.2.4              png_0.1-7                  
[81] vctrs_0.5.0                 tzdb_0.3.0                 
[83] cellranger_1.1.0            gtable_0.3.1               
[85] purrr_1.0.1                 tidyr_1.2.1                
[87] assertthat_0.2.1            cachem_1.0.6               
[89] ggplot2_3.4.0               xfun_0.34                  
[91] janitor_2.1.0               broom_1.0.1                
[93] restfulr_0.0.15             tibble_3.1.8               
[95] GenomicAlignments_1.34.0    memoise_2.0.1              
[97] writexl_1.4.2               timechange_0.1.1           
[99] ellipsis_0.3.2    


> library(BiocManager)
> version()
[1] ‘3.16’
```

**Comment by lshep** [comment] 2023-05-17 17:12
https://github.com/Bioconductor/GenomicFeatures/blob/devel/R/makeTxDbFromBiomart.R#L46   returns FALSE so it ends up using useEnsemblGenomes https://github.com/Bioconductor/GenomicFeatures/blob/devel/R/makeTxDbFromBiomart.R#L49  without taking into account host ---  @grimbough any advice on if this should be changed or if it should have expected different input?

**Comment by grimbough** [comment] 2023-05-22 08:29
Looks like `useEnsemblGenomes()` needs some additional arguments to allow use of the archives.  I'll add an option to use a user supplied host argument,

**Comment by hpages** [comment] 2024-01-23 19:05
Did you get a chance to work on this @grimbough?

**Comment by grimbough** [comment] 2024-01-24 13:03
Hopefully this is addressed in biomaRt 2.59.1, which is now in the devel branch.

**Comment by hpages** [comment] 2024-01-28 05:35
Great! Thanks @grimbough 

@timedreamer You should be able to access Ensembl archive versions with **GenomicFeatures** ~1.54.3~ 1.54.2 (release) and 1.55.3 (devel):
```
library(GenomicFeatures)

zmv4_txdb <- makeTxDbFromBiomart(dataset="zmays_eg_gene",
                                 biomart="plants_mart",
                                 host="https://nov2020-plants.ensembl.org")
# Download and preprocess the 'transcripts' data frame ... OK
# Download and preprocess the 'chrominfo' data frame ... OK
# Download and preprocess the 'splicings' data frame ... OK
# Download and preprocess the 'genes' data frame ... OK
# Prepare the 'metadata' data frame ... OK
# Make the TxDb object ... OK

zmv4_txdb
# TxDb object:
## Db type: TxDb
## Supporting package: GenomicFeatures
## Data source: BioMart
## Organism: Zea mays
## Taxonomy ID: 4577
## Resource URL: nov2020-plants.ensembl.org:443
## BioMart database: plants_mart
## BioMart database version: Ensembl Plants Genes 49
## BioMart dataset: zmays_eg_gene
## BioMart dataset description: Zea mays genes (B73 RefGen_v4)
## BioMart dataset version: B73 RefGen_v4
## Full dataset: yes
## miRBase build ID: NA
## Nb of transcripts: 138424
## Db created by: GenomicFeatures package from Bioconductor
## Creation time: 2024-01-27 21:32:02 -0800 (Sat, 27 Jan 2024)
## GenomicFeatures version at creation time: 1.55.3
## RSQLite version at creation time: 2.3.5
## DBSCHEMAVERSION: 1.2
```
Both new versions of **GenomicFeatures** will become available in BioC 3.18 (release) and 3.19 (devel) via `BiocManager::install()` early next week.

Cheers,
H.

**Comment by grimbough** [comment] 2024-01-29 09:16
I don't think I added this support for biomaRt in BioC 3.18, so I'm not sure if it'll work there.  Seems more like a new feature and API change than a bug fix.

**Comment by hpages** [comment] 2024-01-29 14:24
@grimbough Would you consider adding it to BioC 3.18? Problem is that `makeTxDbFromBiomart()` already switched from `useMart` to `useEnsembl`/`useEnsemblGenomes` there so lack of `host` argument in `useEnsemblGenomes()` translates into a regression for `makeTxDbFromBiomart()`. Unless I switch back to `useMart` in BioC 3.18 but I'd rather avoid that.

I can submit a PR if you want.

Thanks

**Comment by grimbough** [comment] 2024-01-29 15:33
I'm sure I can just cherry pick the changes and put them in 3.18.  I'll do it in the next day or so. I just wanted to point out that it hadn't happened yet and let you know why.  I guess it now becomes a bug fix if there's now a broken package that needs to functionality :wink:

**Comment by hpages** [comment] 2024-01-29 18:24
That would be awesome. Thanks!

**Comment by grimbough** [comment] 2024-01-30 11:22
This is now done in biomaRt 2.58.2.  Let me know if you run into any issues.

**Comment by hpages** [comment] 2024-01-30 21:10
Thanks Mike. Hopefully things will go smoothly tomorrow at https://bioconductor.org/checkResults/3.18/bioc-LATEST/GenomicFeatures/

**Comment by hpages** [comment] 2024-02-01 18:02
Yeahh! https://bioconductor.org/checkResults/3.18/bioc-LATEST/GenomicFeatures/ :tada:

**Closed as completed by hpages** 2024-02-01 18:02 UTC
